import { z } from "zod";

// M3-B grounded-answer contracts.
//
// Architecture rule (approved correction): the visible answer is RENDERED BY
// CODE from validated sections + claims + citations. The model never
// produces free-form factual prose that reaches the user directly, and it
// never produces documentId / documentName / page / chunkId / citationId /
// similarityScore / evidenceStatus / reviewRequired — those are code-owned.

// ---------------------------------------------------------------------------
// Model draft (the ONLY thing the model produces, via strict generateObject)

export const EvidenceHandleSchema = z.string().regex(/^E\d{1,2}$/);

export const QuoteSelectionSchema = z.object({
  handle: EvidenceHandleSchema,
  quote: z.string().min(1).max(300), // must be an exact normalized substring of the chunk — code-verified
}).strict();

export const DraftClaimSchema = z.object({
  claimId: z.string().regex(/^c\d{1,2}$/), // deterministic within the draft
  text: z.string().min(1).max(500),
  factual: z.boolean(), // code may force true (numbers, negative product facts) — never force false
  evidenceHandles: z.array(EvidenceHandleSchema),
  quoteSelections: z.array(QuoteSelectionSchema),
}).strict();
export type DraftClaim = z.infer<typeof DraftClaimSchema>;

export const DraftSectionSchema = z.object({
  heading: z.string().max(120).nullable(),
  claimIds: z.array(z.string().regex(/^c\d{1,2}$/)),
  // Structural/conversational text only — must introduce no product, numeric,
  // legal, tax, coverage, premium, fee, guarantee, eligibility or suitability
  // fact. Deterministically guarded in validation.
  nonFactualText: z.string().max(300).nullable(),
}).strict();
export type DraftSection = z.infer<typeof DraftSectionSchema>;

// The facts the user actually requested, decomposed. Code recomputes
// `supported` from validated claims — the model cannot mark a facet
// supported without a surviving validated claim that states the fact.
export const RequestedFacetSchema = z.object({
  facetId: z.string().regex(/^f\d{1,2}$/),
  description: z.string().min(1).max(200),
  required: z.boolean(),
  supportedByClaimIds: z.array(z.string().regex(/^c\d{1,2}$/)),
}).strict();
export type RequestedFacet = z.infer<typeof RequestedFacetSchema>;

export const ModelDraftSchema = z.object({
  language: z.enum(["zh", "en"]),
  requestedFacets: z.array(RequestedFacetSchema).min(1).max(8),
  sections: z.array(DraftSectionSchema).min(1).max(10),
  claims: z.array(DraftClaimSchema).max(20),
  // Ancillary, nice-to-know gaps only. Material gaps are computed by code
  // from unsupported required facets and can never be model-invented.
  missingInformation: z.array(z.string().min(1).max(300)).max(10),
  suggestedNextStep: z.string().max(300).nullable(),
}).strict();
export type ModelDraft = z.infer<typeof ModelDraftSchema>;

export const ValidatedFacetSchema = z.object({
  facetId: z.string(),
  description: z.string(),
  required: z.boolean(),
  supported: z.boolean(), // code-computed from validated claims
  claimIds: z.array(z.string()),
});
export type ValidatedFacet = z.infer<typeof ValidatedFacetSchema>;

// ---------------------------------------------------------------------------
// Validated output (code-owned)

export const ValidatedClaimSchema = z.object({
  claimId: z.string(),
  text: z.string(),
  factual: z.boolean(),
  citationIds: z.array(z.string()),
});
export type ValidatedClaim = z.infer<typeof ValidatedClaimSchema>;

export const CitationSchema = z.object({
  citationId: z.string().regex(/^cit_\d{3}$/), // generated by code
  documentId: z.string(),
  documentName: z.string(),
  productName: z.string(),
  chunkId: z.string(),
  pageStart: z.number().int().min(1),
  pageEnd: z.number().int().min(1),
  section: z.string(),
  quote: z.string().min(1).max(300),
  claimIds: z.array(z.string()).min(1),
});
export type Citation = z.infer<typeof CitationSchema>;

export const RefusalReasonSchema = z.enum([
  "NOT_IN_KNOWLEDGE_BASE",
  "INSUFFICIENT_EVIDENCE",
  "QUERY_TOO_BROAD",
  "CONFLICTING_EVIDENCE",
  "PROMPT_INJECTION_SUSPECTED",
  "FINAL_RECOMMENDATION_REQUESTED",
  "GUARANTEE_REQUESTED",
  "ILLUSTRATION_VALUE_REQUESTED",
  "OUT_OF_KB_ESTIMATION_REQUEST",
  "LEGAL_TAX_ADVICE_REQUESTED",
  "MODEL_OUTPUT_INVALID",
  "OFF_TOPIC",
]);
export type RefusalReason = z.infer<typeof RefusalReasonSchema>;

export const RefusalSchema = z.object({
  isRefusal: z.boolean(),
  reasonCode: RefusalReasonSchema.nullable(),
  message: z.string().nullable(),
  knownFacts: z.array(z.string()), // texts of VALIDATED claims only
  missingInformation: z.array(z.string()),
  suggestedNextStep: z.string().nullable(),
});
export type Refusal = z.infer<typeof RefusalSchema>;

export const EvidenceStatusSchema = z.enum(["strong", "partial", "insufficient"]);
export type EvidenceStatus = z.infer<typeof EvidenceStatusSchema>;

export const GroundedAnswerSchema = z.object({
  answer: z.string(), // rendered by code from validated claims/sections — never trusted from the model
  language: z.enum(["zh", "en"]),
  claims: z.array(ValidatedClaimSchema),
  citations: z.array(CitationSchema),
  requestedFacets: z.array(ValidatedFacetSchema),
  missingInformation: z.array(z.string()), // material first, then ancillary
  materialMissingInformation: z.array(z.string()), // unsupported required facets (code-derived)
  refusal: RefusalSchema,
  evidenceStatus: EvidenceStatusSchema,
  reviewRequired: z.boolean(),
  reviewReasons: z.array(z.string()),
  meta: z.object({
    retrievalId: z.string(),
    answerModel: z.string(),
    promptVersion: z.number().int(),
    thresholdsVersion: z.number().int(),
    latencyMs: z.number().int(),
    retryCount: z.number().int().min(0).max(1),
    citationCoverage: z.number().min(0).max(1),
    unsupportedClaimCount: z.number().int().min(0),
  }),
});
export type GroundedAnswer = z.infer<typeof GroundedAnswerSchema>;
