import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ManifestSchema } from "../lib/schemas";

// Copies the three approved fictional-product PDFs into public/documents/
// for browser access. data/fictional-products/generated/ stays authoritative;
// public/documents/ is a git-ignored build artifact regenerated by the
// predev/prebuild hooks. Every copy is verified against the manifest sha —
// an unverified PDF is never served.

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIR = join(ROOT, "data/fictional-products/generated");
const PUBLIC_DIR = join(ROOT, "public/documents");

const manifest = ManifestSchema.parse(
  JSON.parse(readFileSync(join(ROOT, "data/fictional-products/manifest.json"), "utf8")),
);

mkdirSync(PUBLIC_DIR, { recursive: true });
let failures = 0;

for (const entry of manifest) {
  const source = join(SOURCE_DIR, entry.file);
  if (!existsSync(source)) {
    console.error(`FAIL ${entry.documentId}: source PDF missing at ${source}`);
    failures++;
    continue;
  }
  const sha = createHash("sha256").update(readFileSync(source)).digest("hex");
  if (sha !== entry.sha256) {
    console.error(
      `FAIL ${entry.documentId}: source PDF sha ${sha.slice(0, 12)}… does not match manifest ` +
        `${entry.sha256.slice(0, 12)}… — regenerate the manifest before serving`,
    );
    failures++;
    continue;
  }
  copyFileSync(source, join(PUBLIC_DIR, entry.file));
  console.log(`ok ${entry.documentId} -> /documents/${entry.file} (${entry.pages} pages)`);
}

if (failures > 0) {
  console.error(`${failures} PDF(s) failed verification; public/documents is incomplete.`);
  process.exit(1);
}
console.log(`Synced ${manifest.length} verified PDFs to public/documents/.`);
